import { FieldPlot, WeatherDay, IrrigationZone, CommodityPrice, MachineryItem, FarmTask } from '../types/farm';

export const INITIAL_FIELDS: FieldPlot[] = [
  {
    id: 'f-1',
    name: 'North Prairie Sector A',
    code: 'NP-01',
    crop: 'Corn (Field Grain)',
    variety: 'Pioneer P1197AM',
    acres: 320,
    shape: 'rectangle',
    coordinates: [
      { x: 40, y: 30 },
      { x: 260, y: 30 },
      { x: 260, y: 170 },
      { x: 40, y: 170 },
    ],
    plantedDate: '2026-04-18',
    expectedHarvest: '2026-10-12',
    growthStage: 'R1 Silking',
    healthStatus: 'optimal',
    ndviMean: 0.84,
    soilMoistureVwc: 31.2,
    surfaceTempC: 23.8,
    elevationM: 245,
    expectedYieldBuPerAcre: 218,
    telemetry: {
      depth10cmMoisture: 33.4,
      depth30cmMoisture: 30.8,
      depth60cmMoisture: 29.5,
      soilTemp: 21.2,
      ph: 6.6,
      organicMatter: 3.8,
      cec: 18.5,
      nitrogenPpm: 48,
      phosphorusPpm: 32,
      potassiumPpm: 195,
    },
    notes: 'Canopy closed uniformly. High leaf chlorophyll reflectance. Drone survey confirmed zero lodging.'
  },
  {
    id: 'f-2',
    name: 'South Center Pivot 01',
    code: 'SCP-01',
    crop: 'Soybeans (Non-GMO)',
    variety: 'Asgrow AG27XF0',
    acres: 280,
    shape: 'pivot',
    coordinates: [
      { x: 420, y: 150 },
    ],
    centerRadius: 110,
    plantedDate: '2026-05-02',
    expectedHarvest: '2026-09-28',
    growthStage: 'R3 Pod Development',
    healthStatus: 'optimal',
    ndviMean: 0.79,
    soilMoistureVwc: 28.5,
    surfaceTempC: 25.1,
    elevationM: 238,
    expectedYieldBuPerAcre: 64,
    telemetry: {
      depth10cmMoisture: 28.2,
      depth30cmMoisture: 28.9,
      depth60cmMoisture: 28.4,
      soilTemp: 22.8,
      ph: 6.8,
      organicMatter: 3.4,
      cec: 16.2,
      nitrogenPpm: 24,
      phosphorusPpm: 28,
      potassiumPpm: 170,
    },
    notes: 'Pivot completing 360-degree pass. Rhizobium nodulation active and healthy pink interior.'
  },
  {
    id: 'f-3',
    name: 'Highland Ridge Block',
    code: 'HR-03',
    crop: 'Hard Red Winter Wheat',
    variety: 'WB4401 CL Plus',
    acres: 190,
    shape: 'polygon',
    coordinates: [
      { x: 310, y: 30 },
      { x: 540, y: 30 },
      { x: 510, y: 120 },
      { x: 280, y: 120 },
    ],
    plantedDate: '2025-10-10',
    expectedHarvest: '2026-07-15',
    growthStage: 'Late Grain Fill (Dough Stage)',
    healthStatus: 'moderate',
    ndviMean: 0.62,
    soilMoistureVwc: 22.1,
    surfaceTempC: 27.6,
    elevationM: 268,
    expectedYieldBuPerAcre: 82,
    telemetry: {
      depth10cmMoisture: 19.8,
      depth30cmMoisture: 22.5,
      depth60cmMoisture: 24.1,
      soilTemp: 24.5,
      ph: 6.4,
      organicMatter: 2.9,
      cec: 14.1,
      nitrogenPpm: 18,
      phosphorusPpm: 22,
      potassiumPpm: 155,
    },
    notes: 'Moderate water stress on upper terrace knoll due to thin topsoil layer. Kernel maturity progressing well.'
  },
  {
    id: 'f-4',
    name: 'Eastern Valley Pivot 02',
    code: 'EVP-02',
    crop: 'Corn (Sweet & Silage)',
    variety: 'DeKalb DKC64-35',
    acres: 240,
    shape: 'pivot',
    coordinates: [
      { x: 670, y: 140 },
    ],
    centerRadius: 95,
    plantedDate: '2026-04-24',
    expectedHarvest: '2026-09-18',
    growthStage: 'V12 Rapid Vegetative',
    healthStatus: 'moderate',
    ndviMean: 0.68,
    soilMoistureVwc: 25.4,
    surfaceTempC: 26.2,
    elevationM: 232,
    expectedYieldBuPerAcre: 195,
    telemetry: {
      depth10cmMoisture: 23.9,
      depth30cmMoisture: 25.6,
      depth60cmMoisture: 26.7,
      soilTemp: 23.4,
      ph: 6.3,
      organicMatter: 3.1,
      cec: 15.8,
      nitrogenPpm: 32,
      phosphorusPpm: 26,
      potassiumPpm: 168,
    },
    notes: 'Slight nitrogen deficiency chlorosis detected on eastern quadrant. Scheduled for fertigation pass.'
  },
  {
    id: 'f-5',
    name: 'Orchard Block 04 (Apples)',
    code: 'OB-04',
    crop: 'Honeycrisp & Gala Apples',
    variety: 'High-Density Trellis M.9',
    acres: 85,
    shape: 'rectangle',
    coordinates: [
      { x: 40, y: 200 },
      { x: 230, y: 200 },
      { x: 230, y: 310 },
      { x: 40, y: 310 },
    ],
    plantedDate: '2022-04-10',
    expectedHarvest: '2026-09-20',
    growthStage: 'Fruit Sizing (48mm Caliper)',
    healthStatus: 'optimal',
    ndviMean: 0.88,
    soilMoistureVwc: 34.0,
    surfaceTempC: 22.4,
    elevationM: 252,
    expectedYieldBuPerAcre: 620, // equivalent bu or boxes
    telemetry: {
      depth10cmMoisture: 35.1,
      depth30cmMoisture: 34.2,
      depth60cmMoisture: 32.8,
      soilTemp: 20.6,
      ph: 6.7,
      organicMatter: 4.2,
      cec: 21.0,
      nitrogenPpm: 52,
      phosphorusPpm: 38,
      potassiumPpm: 220,
    },
    notes: 'Micro-drip pulse irrigation running on 4-hour cycle. High sugar brix accumulation trajectory.'
  },
  {
    id: 'f-6',
    name: 'Lower Creek Bottoms',
    code: 'LCB-06',
    crop: 'Alfalfa (High Protein)',
    variety: 'HarvXtra Trait 008',
    acres: 140,
    shape: 'polygon',
    coordinates: [
      { x: 270, y: 220 },
      { x: 470, y: 200 },
      { x: 530, y: 300 },
      { x: 280, y: 310 },
    ],
    plantedDate: '2024-08-15',
    expectedHarvest: '2026-07-02',
    growthStage: 'Late Bud (Cut 2 Imminent)',
    healthStatus: 'optimal',
    ndviMean: 0.86,
    soilMoistureVwc: 32.8,
    surfaceTempC: 23.0,
    elevationM: 228,
    expectedYieldBuPerAcre: 7.2, // tons/acre
    telemetry: {
      depth10cmMoisture: 32.1,
      depth30cmMoisture: 33.5,
      depth60cmMoisture: 32.8,
      soilTemp: 21.8,
      ph: 7.0,
      organicMatter: 4.0,
      cec: 19.4,
      nitrogenPpm: 44,
      phosphorusPpm: 34,
      potassiumPpm: 240,
    },
    notes: '2nd cut scheduled for 3 days post dry-down window. Projected relative feed value (RFV) > 185.'
  }
];

export const MOCK_WEATHER_FORECAST: WeatherDay[] = [
  {
    date: '2026-09-23',
    dayName: 'Today',
    tempHigh: 27,
    tempLow: 15,
    condition: 'sunny',
    precipChance: 5,
    precipMm: 0,
    windSpeedKmh: 9,
    windDirection: 'SSE',
    humidityPct: 54,
    deltaT: 4.8,
    spraySuitability: 'optimal',
    et0: 4.6,
    gddAccumulated: 18.5,
  },
  {
    date: '2026-09-24',
    dayName: 'Tomorrow',
    tempHigh: 29,
    tempLow: 17,
    condition: 'partly_cloudy',
    precipChance: 15,
    precipMm: 0.4,
    windSpeedKmh: 14,
    windDirection: 'S',
    humidityPct: 58,
    deltaT: 5.4,
    spraySuitability: 'optimal',
    et0: 4.9,
    gddAccumulated: 20.0,
  },
  {
    date: '2026-09-25',
    dayName: 'Friday',
    tempHigh: 31,
    tempLow: 19,
    condition: 'windy',
    precipChance: 25,
    precipMm: 1.2,
    windSpeedKmh: 28,
    windDirection: 'SW',
    humidityPct: 42,
    deltaT: 8.6,
    spraySuitability: 'unsuitable',
    et0: 5.8,
    gddAccumulated: 22.5,
  },
  {
    date: '2026-09-26',
    dayName: 'Saturday',
    tempHigh: 24,
    tempLow: 13,
    condition: 'rain',
    precipChance: 85,
    precipMm: 18.5,
    windSpeedKmh: 18,
    windDirection: 'NNW',
    humidityPct: 88,
    deltaT: 2.1,
    spraySuitability: 'unsuitable',
    et0: 2.1,
    gddAccumulated: 12.0,
  },
  {
    date: '2026-09-27',
    dayName: 'Sunday',
    tempHigh: 22,
    tempLow: 11,
    condition: 'partly_cloudy',
    precipChance: 20,
    precipMm: 0.2,
    windSpeedKmh: 11,
    windDirection: 'NW',
    humidityPct: 62,
    deltaT: 4.2,
    spraySuitability: 'marginal',
    et0: 3.4,
    gddAccumulated: 11.5,
  },
  {
    date: '2026-09-28',
    dayName: 'Monday',
    tempHigh: 25,
    tempLow: 13,
    condition: 'sunny',
    precipChance: 5,
    precipMm: 0,
    windSpeedKmh: 8,
    windDirection: 'WNW',
    humidityPct: 50,
    deltaT: 4.5,
    spraySuitability: 'optimal',
    et0: 4.2,
    gddAccumulated: 16.0,
  },
  {
    date: '2026-09-29',
    dayName: 'Tuesday',
    tempHigh: 26,
    tempLow: 14,
    condition: 'sunny',
    precipChance: 0,
    precipMm: 0,
    windSpeedKmh: 10,
    windDirection: 'SW',
    humidityPct: 52,
    deltaT: 4.7,
    spraySuitability: 'optimal',
    et0: 4.4,
    gddAccumulated: 17.0,
  },
];

export const INITIAL_IRRIGATION_ZONES: IrrigationZone[] = [
  {
    id: 'iz-1',
    name: 'Sector Pivot 01 (South)',
    fieldId: 'f-2',
    fieldName: 'South Center Pivot 01 (Soybeans)',
    type: 'Center Pivot',
    status: 'active',
    applicationRateMmPerHour: 6.2,
    targetMoisturePct: 32.0,
    currentMoisturePct: 28.5,
    durationMinutes: 240,
    totalDeliveredM3: 4180,
    efficiencyRatingPct: 92,
  },
  {
    id: 'iz-2',
    name: 'Eastern Pivot 02 (Corn)',
    fieldId: 'f-4',
    fieldName: 'Eastern Valley Pivot 02 (Corn)',
    type: 'Center Pivot',
    status: 'scheduled',
    applicationRateMmPerHour: 5.5,
    targetMoisturePct: 30.0,
    currentMoisturePct: 25.4,
    durationMinutes: 180,
    totalDeliveredM3: 3120,
    efficiencyRatingPct: 91,
  },
  {
    id: 'iz-3',
    name: 'Orchard Micro-Drip Sub-manifold A',
    fieldId: 'f-5',
    fieldName: 'Orchard Block 04 (Apples)',
    type: 'Subsurface Drip',
    status: 'active',
    applicationRateMmPerHour: 2.8,
    targetMoisturePct: 35.0,
    currentMoisturePct: 34.0,
    durationMinutes: 120,
    totalDeliveredM3: 860,
    efficiencyRatingPct: 96,
  },
  {
    id: 'iz-4',
    name: 'North Prairie VRA Big-Gun Line',
    fieldId: 'f-1',
    fieldName: 'North Prairie Sector A (Corn)',
    type: 'Variable Rate Gun',
    status: 'idle',
    applicationRateMmPerHour: 8.0,
    targetMoisturePct: 33.0,
    currentMoisturePct: 31.2,
    durationMinutes: 0,
    totalDeliveredM3: 1540,
    efficiencyRatingPct: 87,
  },
];

export const COMMODITY_PRICES: CommodityPrice[] = [
  {
    symbol: 'ZC*1',
    name: 'CBOT Corn Futures',
    contract: 'Dec 2026',
    price: 4.48,
    unit: '$/bushel',
    change: 0.065,
    changePct: 1.47,
    high: 4.52,
    low: 4.41,
    volume: '142,850',
  },
  {
    symbol: 'ZS*1',
    name: 'CBOT Soybean Futures',
    contract: 'Nov 2026',
    price: 11.24,
    unit: '$/bushel',
    change: -0.12,
    changePct: -1.06,
    high: 11.38,
    low: 11.18,
    volume: '98,420',
  },
  {
    symbol: 'KE*1',
    name: 'KC Hard Red Winter Wheat',
    contract: 'Jul 2026',
    price: 5.86,
    unit: '$/bushel',
    change: 0.08,
    changePct: 1.38,
    high: 5.92,
    low: 5.76,
    volume: '43,100',
  },
  {
    symbol: 'CT*1',
    name: 'ICE Cotton No. 2',
    contract: 'Oct 2026',
    price: 78.42,
    unit: '¢/lb',
    change: 0.95,
    changePct: 1.23,
    high: 79.10,
    low: 77.20,
    volume: '22,400',
  },
  {
    symbol: 'ZO*1',
    name: 'CBOT Oats Futures',
    contract: 'Sep 2026',
    price: 3.65,
    unit: '$/bushel',
    change: -0.02,
    changePct: -0.54,
    high: 3.71,
    low: 3.62,
    volume: '7,890',
  },
  {
    symbol: 'UREA-N',
    name: 'Urea Fertilizer (FOB NOLA)',
    contract: 'Spot Cash',
    price: 345.0,
    unit: '$/short ton',
    change: -5.0,
    changePct: -1.43,
    high: 352.0,
    low: 342.0,
    volume: 'N/A',
  },
];

export const MACHINERY_FLEET: MachineryItem[] = [
  {
    id: 'm-1',
    name: 'John Deere 8R 370',
    model: '8R Series Gen 4',
    category: 'Tractor',
    status: 'operating',
    operator: 'Dale Vance',
    currentField: 'NP-01 (North Prairie)',
    fuelPct: 74,
    engineHours: 1240,
    gpsAccuracy: 'RTK (±1.5 cm)',
  },
  {
    id: 'm-2',
    name: 'Agrifac Condor Endurance',
    model: '54m Boom AirFlowPlus',
    category: 'Sprayer',
    status: 'standby',
    operator: 'Elena Ramos',
    currentField: 'Yard Staging',
    fuelPct: 88,
    engineHours: 620,
    gpsAccuracy: 'RTK Sub-inch',
  },
  {
    id: 'm-3',
    name: 'Case IH Axial-Flow 8250',
    model: 'Track Combine Tier 4B',
    category: 'Combine Harvester',
    status: 'maintenance',
    operator: 'Marcus Chen',
    currentField: 'Workshop Bay 2',
    fuelPct: 45,
    engineHours: 2180,
    gpsAccuracy: 'WAAS GPS',
  },
  {
    id: 'm-4',
    name: 'Kinze 4905 Blue Drive',
    model: '24-Row 30" Planter',
    category: 'Planter',
    status: 'standby',
    operator: 'Unassigned',
    currentField: 'Equipment Shed A',
    fuelPct: 100,
    engineHours: 410,
    gpsAccuracy: 'Blue Vantage Dual RTK',
  },
];

export const FARM_TASKS: FarmTask[] = [
  {
    id: 't-1',
    title: 'Scout upper canopy for Northern Corn Leaf Blight threshold',
    field: 'NP-01 (North Prairie Sector A)',
    priority: 'high',
    assignedTo: 'Elena Ramos (CCA)',
    dueDate: 'Today · 16:00',
    completed: false,
    type: 'Scouting',
  },
  {
    id: 't-2',
    title: 'Check Center Pivot 01 nozzle alignment & end-gun pressure',
    field: 'SCP-01 (South Pivot)',
    priority: 'medium',
    assignedTo: 'Dale Vance',
    dueDate: 'Tomorrow · 09:00',
    completed: false,
    type: 'Irrigation',
  },
  {
    id: 't-3',
    title: 'Prepare foliar fungicide mix (Azoxystrobin + Difenoconazole)',
    field: 'Chemical Mixing Pad',
    priority: 'high',
    assignedTo: 'Marcus Chen',
    dueDate: 'Tomorrow · 07:00',
    completed: true,
    type: 'Spraying',
  },
  {
    id: 't-4',
    title: 'Post-emergence side-dress UAN-32 variable rate application',
    field: 'EVP-02 (Eastern Valley)',
    priority: 'medium',
    assignedTo: 'Dale Vance',
    dueDate: 'Sep 25 · 11:00',
    completed: false,
    type: 'Fertilization',
  },
  {
    id: 't-5',
    title: 'Calibrate combine yield monitor sensors for winter wheat',
    field: 'HR-03 (Highland Ridge)',
    priority: 'low',
    assignedTo: 'Elena Ramos',
    dueDate: 'Sep 27 · 14:00',
    completed: false,
    type: 'Harvesting',
  }
];

export const SAMPLE_CROP_CASES = [
  {
    id: 'case-corn-nclb',
    name: 'Corn · Cigar-shaped Gray Folio Blotch',
    crop: 'Corn (Field Maize)',
    stage: 'R1 Silking / Flowering',
    symptoms: 'Long elliptical grayish-green water-soaked lesions progressing to tan brown necrotic blotches on lower and ear leaves with dark fungal conidia.',
    suspected: 'Exserohilum turcicum (Northern Corn Leaf Blight)',
    severity: 'Moderate (Index 6.2/10)'
  },
  {
    id: 'case-wheat-rust',
    name: 'Winter Wheat · Yellow Stripe Rust',
    crop: 'Hard Red Winter Wheat',
    stage: 'Flag Leaf Stage (Zadoks 39)',
    symptoms: 'Linear rows of bright yellow-orange pustules (uredinia) forming stripes between leaf veins, premature leaf desiccation and chlorotic necrosis.',
    suspected: 'Puccinia striiformis f. sp. tritici (Stripe Rust)',
    severity: 'High (Index 7.8/10)'
  },
  {
    id: 'case-soy-sds',
    name: 'Soybean · Interveinal Chlorosis & Leaf Scorching',
    crop: 'Soybeans',
    stage: 'R4 Full Pod Stage',
    symptoms: 'Mottled yellow spots on leaves merging into brown necrotic tissue between main veins while veins remain bright green. Pith of taproot shows white healthy center with cortical browning.',
    suspected: 'Fusarium virguliforme (Sudden Death Syndrome)',
    severity: 'High (Index 7.4/10)'
  },
  {
    id: 'case-apple-scab',
    name: 'Apple Orchard · Olive-Black Velvety Scab',
    crop: 'Honeycrisp Apples',
    stage: 'Fruit Sizing',
    symptoms: 'Dull olive-green to black velvety spots on leaf surface and young fruit skin, with corky cracking and distorted fruit growth.',
    suspected: 'Venturia inaequalis (Apple Scab)',
    severity: 'Moderate (Index 5.5/10)'
  }
];
